// Code generated by xgen. DO NOT EDIT.
// Code generated by xgen. DO NOT EDIT.
// Code generated by xgen. DO NOT EDIT.

package users

import (
	"common-toolkits-v1/GormXGens/config"
	"common-toolkits-v1/xgen_test/model/entity"
	"context"
	"database/sql"
	"gorm.io/gorm"
)

type userQuery struct {
	db        gorm.DB
	tableName string
}

func newQuery(db *gorm.DB) *userQuery {
	model := entity.User{}
	tableName := model.TableName()
	tableDB := db.Table(tableName)
	return &userQuery{
		db:        *tableDB,
		tableName: tableName,
	}
}

// GetTableName table名称
func (u userQuery) GetTableName() string {
	return u.tableName
}

// 获取DB操作对象
func (u userQuery) GetuserQueryDB() gorm.DB {
	return u.db
}

// GetList 获取列表
func (u userQuery) GetList(ctx context.Context, opts ...config.DBFunc) ([]*entity.User, error) {
	db := u.db.WithContext(ctx)
	for _, f := range opts {
		err := f(db)
		if err != nil {
			return nil, err
		}
	}
	var models []*entity.User
	db.Find(&models)
	return models, nil
}

// GetRow 获取Row的数据
func (u userQuery) GetRow(ctx context.Context, opts ...config.DBFunc) (*sql.Row, error) {
	db := u.db.WithContext(ctx)
	for _, f := range opts {
		err := f(db)
		if err != nil {
			return nil, err
		}
	}
	row := db.Row()
	return row, nil
}

// GetRows 获取Rows的数据
func (u userQuery) GetRows(ctx context.Context, opts ...config.DBFunc) (*sql.Rows, error) {
	db := u.db.WithContext(ctx)
	for _, f := range opts {
		err := f(db)
		if err != nil {
			return nil, err
		}
	}
	return db.Rows()
}

// GetUserByID 主键查询
func (u userQuery) GetUserByID(ctx context.Context, ID int32, opts ...config.DBFunc) (*entity.User, error) {
	db := u.db.WithContext(ctx)
	for _, f := range opts {
		err := f(db)
		if err != nil {
			return nil, err
		}
	}
	db.Where("id = ?", ID)
	var models *entity.User
	db.First(&models)
	return models, nil
}

// DeleteByID 主键删除数据
func (u userQuery) DeleteByID(ctx context.Context, ID int32, opts ...config.DBFunc) error {
	db := u.db.WithContext(ctx)
	for _, f := range opts {
		err := f(db)
		if err != nil {
			return err
		}
	}
	tx := db.Delete(&entity.User{
		ID: ID,
	})
	if tx.Error != nil {
		return tx.Error
	}
	return nil
}

// UpdateByID 主键修改数据
func (u userQuery) UpdateByID(ctx context.Context, ID int32, model *any, opts ...config.DBFunc) error {
	db := u.db.WithContext(ctx)
	for _, f := range opts {
		err := f(db)
		if err != nil {
			return err
		}
	}
	db.Where("id = ?", ID)
	result := db.Save(model)
	if err := result.Error; err != nil {
		return err
	}
	return nil
}

// Create 创建数据
func (u userQuery) Create(ctx context.Context, model *any) error {
	db := u.db.WithContext(ctx)
	result := db.Create(model)
	if err := result.Error; err != nil {
		return err
	}
	return nil
}

// Update 修改数据
func (u userQuery) Update(ctx context.Context, model *any, opts ...config.DBFunc) error {
	db := u.db.WithContext(ctx)
	for _, f := range opts {
		err := f(db)
		if err != nil {
			return err
		}
	}
	result := db.Updates(model)
	if err := result.Error; err != nil {
		return err
	}
	return nil
}

// GetListCount Count数量统计
func (u userQuery) GetListCount(ctx context.Context, opts ...config.DBFunc) (int64, error) {
	db := u.db.WithContext(ctx)
	for _, f := range opts {
		err := f(db)
		if err != nil {
			return 0, err
		}
	}
	var count int64
	db.Count(&count)
	if db.Error != nil {
		return 0, db.Error
	}
	return count, nil
}
