// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameApplyLinkDoctor = "apply_link_doctor"

// ApplyLinkDoctor mapped from table <apply_link_doctor>
type ApplyLinkDoctor struct {
	ID         int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:id信息" json:"id"`                       // id信息
	DoctorID   int32     `gorm:"column:doctor_id;type:int;not null;comment:医生id" json:"doctor_id"`                              // 医生id
	ResidentID int32     `gorm:"column:resident_id;type:int;not null;comment:用户信息" json:"resident_id"`                          // 用户信息
	ApplyType  int32     `gorm:"column:apply_type;type:int;not null;comment:关联类型(1:家庭医生2:社区医生3:其他医生,0:其他关系)" json:"apply_type"` // 关联类型(1:家庭医生2:社区医生3:其他医生,0:其他关系)
	IsComplete int32     `gorm:"column:is_complete;type:int;not null;comment:处理结果(1:取消，2:同意，3:拒绝)" json:"is_complete"`          // 处理结果(1:取消，2:同意，3:拒绝)
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;comment:创建时间" json:"create_time"`                     // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;comment:更新时间" json:"update_time"`                     // 更新时间
	IsDelete   int32     `gorm:"column:is_delete;type:int;not null;comment:删除标记" json:"is_delete"`                              // 删除标记
}

// TableName ApplyLinkDoctor's table name
func (*ApplyLinkDoctor) TableName() string {
	return TableNameApplyLinkDoctor
}
