// Code generated by xgen. DO NOT EDIT.
// Code generated by xgen. DO NOT EDIT.
// Code generated by xgen. DO NOT EDIT.

package {{.DoPackage}}
import (
	"common-toolkits-v1/GormXGens/config"
	"{{.ModelLinkPath}}"
	"gorm.io/gorm"
)

type {{.DoName}} struct {
	db        gorm.DB
	tableName string
}

func newQuery(db *gorm.DB) *{{.DoName}} {
	model := {{.ModelPackage}}.{{.ModelName}}{}
	tableName := model.TableName()
	tableDB := db.Table(tableName)
	return &{{.DoName}}{
		db:        *tableDB,
		tableName: tableName,
	}
}

// GetTableName table名称
func (u {{.DoName}}) GetTableName() string {
	return u.tableName
}

// 获取DB操作对象
func (u {{.DoName}}) Get{{.DoName}}DB() gorm.DB {
	return u.db
}

// GetList 获取列表
func (u {{.DoName}}) GetList(opts ...config.DBFunc) ([]*{{.ModelPackage}}.{{.ModelName}}, error) {
	db := u.db
	for _, f := range opts {
		f(&db)
	}
	var models []*{{.ModelPackage}}.{{.ModelName}}
	db.Find(&models)
	return models, nil
}